"""забыл че сделал но надо короче

Revision ID: 9057e3a1452a
Revises: a296fd9f5915
Create Date: 2024-07-26 16:39:27.824952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9057e3a1452a'
down_revision: Union[str, None] = 'a296fd9f5915'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('date_created', sa.DateTime(timezone=True), nullable=False))
    op.add_column('comments', sa.Column('date_modified', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint('fk_t_groups_workspaces_id_workspace', 't_groups', type_='foreignkey')
    op.drop_column('t_groups', 'workspace')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_groups', sa.Column('workspace', sa.BIGINT(), autoincrement=False, nullable=False))
    op.create_foreign_key('fk_t_groups_workspaces_id_workspace', 't_groups', 'workspaces', ['workspace'], ['id'])
    op.drop_column('comments', 'date_modified')
    op.drop_column('comments', 'date_created')
    # ### end Alembic commands ###
