"""permission system refactor and enum fix

Revision ID: a296fd9f5915
Revises: ee9df1b21bf2
Create Date: 2024-07-26 10:04:55.532457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a296fd9f5915'
down_revision: Union[str, None] = 'ee9df1b21bf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('avatar', sa.Text(), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('date_joined', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workspaces',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('boards',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('workspace', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('slug_ticker', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['workspace'], ['workspaces.id'], name='fk_boards_workspaces_id_workspace'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('i_permissions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('permission', sa.BigInteger(), nullable=False),
    sa.Column('instance_class', sa.String(length=50), nullable=False),
    sa.Column('instance_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['permission'], ['permissions.id'], name='fk_i_permissions_permissions_id_permission'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('workspace', sa.BigInteger(), nullable=False),
    sa.Column('for_user', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['workspace'], ['workspaces.id'], name='fk_roles_workspaces_id_workspace'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participants',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('workspace', sa.BigInteger(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('role', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['role'], ['roles.id'], name='fk_participants_roles_id_role'),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name='fk_participants_users_id_user'),
    sa.ForeignKeyConstraint(['workspace'], ['workspaces.id'], name='fk_participants_workspaces_id_workspace'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles_ipermissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ipermission', sa.BigInteger(), nullable=True),
    sa.Column('role', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['ipermission'], ['i_permissions.id'], name='fk_roles_ipermissions_i_permissions_ipermission_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role'], ['roles.id'], name='fk_roles_ipermissions_roles_role_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_groups',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('workspace', sa.BigInteger(), nullable=False),
    sa.Column('board', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['board'], ['boards.id'], name='fk_t_groups_boards_id_board'),
    sa.ForeignKeyConstraint(['workspace'], ['workspaces.id'], name='fk_t_groups_workspaces_id_workspace'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('branch', sa.String(length=50), nullable=True),
    sa.Column('creator', sa.BigInteger(), nullable=False),
    sa.Column('group', sa.BigInteger(), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_ending', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['creator'], ['participants.id'], name='fk_tasks_participants_id_creator'),
    sa.ForeignKeyConstraint(['group'], ['t_groups.id'], name='fk_tasks_t_groups_id_group'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('creator', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('task', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['creator'], ['participants.id'], name='fk_comments_participants_id_creator'),
    sa.ForeignKeyConstraint(['task'], ['tasks.id'], name='fk_comments_tasks_id_task'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant', sa.BigInteger(), nullable=True),
    sa.Column('task', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['participant'], ['participants.id'], name='fk_tasks_participants_participants_participant_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task'], ['tasks.id'], name='fk_tasks_participants_tasks_task_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks_participants')
    op.drop_table('comments')
    op.drop_table('tasks')
    op.drop_table('t_groups')
    op.drop_table('roles_ipermissions')
    op.drop_table('participants')
    op.drop_table('roles')
    op.drop_table('i_permissions')
    op.drop_table('boards')
    op.drop_table('workspaces')
    op.drop_table('users')
    op.drop_table('permissions')
    # ### end Alembic commands ###
